<?php

namespace backend\controllers;
use backend\models\StudentMaster;
use backend\models\StudentAdmission;
use kartik\mpdf\Pdf;

class PrintController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionAdmission($id,$adm)
    {
   
          $pdf = new Pdf([
        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
        'orientation'=>'L',
        'destination' => Pdf::DEST_DOWNLOAD,
        'filename' => 'Ordinarypost"'.date('d-m-y').'".pdf',


        'content' =>$this->renderPartial('admission',['id'=>$id,'adm_no'=>$adm]),
        'options' => [
            'title' => 'Labels',
            'subject' => 'Generating Labels',
            'fileame' => 'Ordinarypost.pdf'
        ],
        // 'methods' => [
        //     'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
        //     'SetFooter' => ['|Page {PAGENO}|'],
        // ]
    ]);

    // return the pdf output as per the destination setting
    return $pdf->render(); 
    }

}
