<?php
/**
 * Created by PhpStorm.
 * User: Ritesh Singh
 * Date: 6/26/2016
 * Time: 9:29 AM
 */
namespace backend\controllers;
use yii\web\Controller;
use backend\models\StudentMaster;
use backend\models\AddmissionPaymentDetails;
use backend\models\FeeBreakup;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

Class ReceiptController extends Controller{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionAdmission($id){

        $pay=new AddmissionPaymentDetails();
        $data=$pay->getSlip($id);
     //   echo '<pre>';
       // print_r($data);
       // echo '</pre';exit;
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
            'orientation'=>'P',
            'destination' => Pdf::DEST_DOWNLOAD,
            'filename' => 'AdmissionSlip"'.date('d-m-y h:i:s').'".pdf',


            'content' =>$this->renderPartial('admission',['data'=>$data]),
            'options' => [
                'title' => 'Labels',
                'subject' => 'Generating Labels',
                'fileame' => 'Ordinarypost.pdf'
            ],
            // 'methods' => [
            //     'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
            //     'SetFooter' => ['|Page {PAGENO}|'],
            // ]
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }
}
